# Generated by Django 4.2.3 on 2024-01-13 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='f_name',
            new_name='name',
        ),
    ]
