# Generated by Django 4.2.3 on 2024-01-14 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0002_rename_f_name_department_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(default=0, upload_to='file/covers'),
        ),
    ]
