# Generated by Django 4.2.3 on 2024-01-14 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0003_employee_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='image',
        ),
    ]
